baseurl = "https://blog.tamir.dev/"
title = "Tamir Bahar"
copyright = "Copyright &copy; 2022 - Tamir Bahar"
canonifyurls = true
theme = "hugo-PaperMod"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
name = "Tamir Bahar"
github = "tmr232"
twitter = "tmr232"
stackoverflow = "users/3337893/tmr232"
devto = "tmr232"

[params]
title = "Tamir Bahar"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/"